name: Docs Link Checker

on:
  schedule:
    # Run every day at 12:00 UTC
#    - cron: '0 12 * * *'
# BFP - turn off cron till we know what to do with it. 

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --verbose --config .github/lychee.toml './website/**/*.md'
